import type { Metadata } from "next";
import { Cormorant_Garamond, Lora } from "next/font/google";

import { Header } from "./components";

import "./globals.css";

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${cormorantGaramond.variable} ${lora.variable} antialiased`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
